/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int *
add_1_svc(num *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
printf("Server is listening...\n");
           int n=argp->a;
int  sum=0;
           for(int i=1;i<=n;i++){
sum+=i;
}
result=sum;
	return &result;
}
